ALTER TABLE horas_trabajadas
MODIFY COLUMN cantidad DECIMAL(19, 2) NOT NULL,
MODIFY COLUMN unidad VARCHAR(50) NOT NULL,
MODIFY COLUMN nombre_empleado VARCHAR(255) NOT NULL,
MODIFY COLUMN nombre_proyecto VARCHAR(255) NOT NULL;